package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.entity.LongTermMemory;
import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.exception.RateLimitExceededException;
import com.yizhaoqi.smartpai.service.patent.PatentSearchService;
import com.yizhaoqi.smartpai.service.patent.dto.PatentSearchRequest;
import com.yizhaoqi.smartpai.service.patent.dto.PatentSearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.RejectedExecutionException;
import java.util.regex.Pattern;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final int MAX_CONTEXT_SNIPPET_LEN = 300;
    private static final int MAX_MATCHED_CHUNK_LEN = 800;
    private static final int MAX_EVIDENCE_SNIPPET_LEN = 160;
    private static final int MAX_CONVERSATION_ROUNDS = 5;  // 最多保留5轮对话（10条消息）
    private static final int MAX_MESSAGES = MAX_CONVERSATION_ROUNDS * 2;  // 10条消息
    private static final Pattern PATENT_NUMBER_PATTERN = Pattern.compile("(CN\\s?\\d{6,}[A-Z]?|\\b\\d{10,16}\\b)", Pattern.CASE_INSENSITIVE);
    private static final List<String> PATENT_QUERY_KEYWORDS = List.of(
            "专利", "权利要求", "独立权利要求", "从属权利要求", "说明书", "公开号", "公布号", "公告号",
            "申请号", "申请人", "发明人", "ipc", "保护范围", "技术方案", "技术特征", "实施例",
            "新颖性", "创造性", "侵权", "等同", "摘要", "附图"
    );
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final PatentSearchService patentSearchService;
    private final LlmProviderRouter llmProviderRouter;
    private final RateLimitService rateLimitService;
    private final UsageQuotaService usageQuotaService;
    private final ConversationMemoryService conversationMemoryService;
    private final ThreadPoolTaskExecutor chatMonitorExecutor;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于存储每个会话的引用映射：sessionId -> {referenceNumber -> detail}
    private final Map<String, Map<Integer, ReferenceInfo>> sessionReferenceMappings = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      PatentSearchService patentSearchService,
                      LlmProviderRouter llmProviderRouter,
                      RateLimitService rateLimitService,
                      UsageQuotaService usageQuotaService,
                      ConversationMemoryService conversationMemoryService,
                      @Qualifier("chatMonitorExecutor") ThreadPoolTaskExecutor chatMonitorExecutor) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.patentSearchService = patentSearchService;
        this.llmProviderRouter = llmProviderRouter;
        this.rateLimitService = rateLimitService;
        this.usageQuotaService = usageQuotaService;
        this.conversationMemoryService = conversationMemoryService;
        this.chatMonitorExecutor = chatMonitorExecutor;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            rateLimitService.checkChatByUser(userId);

            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());

            // 2.1 检索长期记忆
            List<Map<String, Object>> historyRecords = getConversationHistoryRecords(conversationId);
            String retrievalQuery = conversationMemoryService.buildRetrievalQuery(userMessage, historyRecords);
            List<LongTermMemory> longTermMemories = conversationMemoryService.retrieveMemories(userId, retrievalQuery, 5);
            String longTermMemoryContext = buildLongTermMemoryContext(longTermMemories);
            logger.debug("检索到 {} 条长期记忆", longTermMemories.size());

            // 3. 执行带权限过滤的检索。专利问题优先走专利结构化索引，普通问题保留原通用 RAG。
            List<SearchResult> searchResults = retrieveRagContext(userMessage, userId);
            logger.debug("搜索结果数量: {}", searchResults.size());
            
            // 4. 构建上下文
            String context = buildContext(searchResults, session.getId(), userMessage);

            // 4.1 合并长期记忆上下文
            if (!longTermMemoryContext.isEmpty()) {
                context = longTermMemoryContext + "\n\n" + context;
            }

            // 5. 调用活动 LLM Provider 并处理流式响应
            logger.info("调用活动 LLM Provider 生成回复");
            llmProviderRouter.streamResponse(userId, userMessage, context, history,
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                });

            // 6. 后台任务检查并标记响应完成
            submitCompletionMonitor(userId, userMessage, conversationId, session, responseFuture);
            
        } catch (RateLimitExceededException e) {
            sendRateLimitMessage(session, e);
            cleanupSessionState(session.getId(), null);
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            cleanupSessionState(session.getId(), e);
        }
    }

    private void submitCompletionMonitor(String userId, String userMessage, String conversationId, WebSocketSession session,
                                         CompletableFuture<String> responseFuture) {
        try {
            chatMonitorExecutor.execute(() -> {
                try {
                    Thread.sleep(3000);
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder == null) {
                        RuntimeException exception = new RuntimeException("响应构建器为空");
                        responseFuture.completeExceptionally(exception);
                        handleError(session, exception);
                        cleanupSessionState(session.getId(), exception);
                        return;
                    }

                    int lastLength = responseBuilder.length();
                    Thread.sleep(2000);
                    if (responseBuilder.length() == lastLength) {
                        finalizeResponse(userId, userMessage, conversationId, session, responseFuture, responseBuilder);
                        return;
                    }

                    for (int i = 0; i < 5; i++) {
                        Thread.sleep(5000);
                        lastLength = responseBuilder.length();
                        Thread.sleep(2000);
                        if (responseBuilder.length() == lastLength) {
                            finalizeResponse(userId, userMessage, conversationId, session, responseFuture, responseBuilder);
                            return;
                        }
                    }

                    if (!responseFuture.isDone()) {
                        finalizeResponse(userId, userMessage, conversationId, session, responseFuture, responseBuilder);
                    }
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    cleanupSessionState(session.getId(), e);
                }
            });
        } catch (RejectedExecutionException ex) {
            logger.warn("聊天监控线程池已满，会话ID: {}", session.getId());
            handleError(session, new RuntimeException("系统繁忙，请稍后重试"));
            cleanupSessionState(session.getId(), ex);
        }
    }

    private void finalizeResponse(String userId, String userMessage, String conversationId, WebSocketSession session,
                                  CompletableFuture<String> responseFuture, StringBuilder responseBuilder) {
        String completeResponse = responseBuilder.toString();
        responseFuture.complete(completeResponse);
        sendCompletionNotification(session);
        updateConversationHistory(conversationId, userId, userMessage, completeResponse, sessionReferenceMappings.get(session.getId()));
        logger.info("对话存储信息 - Redis键: {}, 值: {}", "user:" + userId + ":current_conversation", conversationId);
        cleanupSessionState(session.getId(), null);
        logger.info("消息处理完成，用户ID: {}", userId);
    }

    private void cleanupSessionState(String sessionId, Throwable throwable) {
        responseBuilders.remove(sessionId);
        CompletableFuture<String> future = responseFutures.remove(sessionId);
        if (throwable != null && future != null && !future.isDone()) {
            future.completeExceptionally(throwable);
        }
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        List<Map<String, Object>> records = getConversationHistoryRecords(conversationId);
        List<Map<String, String>> history = new ArrayList<>();
        for (Map<String, Object> message : records) {
            Map<String, String> normalized = new HashMap<>();
            normalized.put("role", String.valueOf(message.getOrDefault("role", "")));
            normalized.put("content", String.valueOf(message.getOrDefault("content", "")));
            Object timestamp = message.get("timestamp");
            if (timestamp != null) {
                normalized.put("timestamp", String.valueOf(timestamp));
            }
            history.add(normalized);
        }
        return history;
    }

    private List<Map<String, Object>> getConversationHistoryRecords(String conversationId) {
        String key = "conversation:" + conversationId;
        try {
            // 使用 Redis List 获取所有消息
            List<String> jsonMessages = redisTemplate.opsForList().range(key, 0, -1);
            if (jsonMessages == null || jsonMessages.isEmpty()) {
                // 尝试从旧格式 String 迁移
                return migrateFromStringFormat(conversationId, key);
            }

            List<Map<String, Object>> history = new ArrayList<>();
            for (String json : jsonMessages) {
                try {
                    Map<String, Object> message = objectMapper.readValue(json,
                            new TypeReference<Map<String, Object>>() {});
                    history.add(message);
                } catch (JsonProcessingException e) {
                    logger.warn("解析单条消息失败: {}, 跳过该条", e.getMessage());
                }
            }
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (Exception e) {
            logger.error("读取对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    /**
     * 从旧 String 格式迁移到 List 格式
     */
    private List<Map<String, Object>> migrateFromStringFormat(String conversationId, String key) {
        try {
            // 尝试作为 String 读取（旧格式）
            String json = redisTemplate.opsForValue().get(key);
            if (json != null && !json.isBlank()) {
                List<Map<String, Object>> history = objectMapper.readValue(json,
                        new TypeReference<List<Map<String, Object>>>() {});
                if (history != null && !history.isEmpty()) {
                    logger.info("检测到旧格式会话数据，开始迁移: conversationId={}, 消息数={}",
                            conversationId, history.size());

                    // 删除旧 String key
                    redisTemplate.delete(key);

                    // 重新以 List 格式写入
                    for (Map<String, Object> msg : history) {
                        String msgJson = objectMapper.writeValueAsString(msg);
                        redisTemplate.opsForList().rightPush(key, msgJson);
                    }

                    // 设置 TTL
                    redisTemplate.expire(key, Duration.ofDays(7));

                    logger.info("会话数据迁移完成: conversationId={}", conversationId);
                    return history;
                }
            }
        } catch (Exception e) {
            logger.warn("迁移旧格式会话数据失败: conversationId={}, error={}", conversationId, e.getMessage());
        }
        return new ArrayList<>();
    }

    private void updateConversationHistory(String conversationId, String userId, String userMessage, String response,
                                           Map<Integer, ReferenceInfo> referenceMapping) {
        String key = "conversation:" + conversationId;
        String currentTimestamp = java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));

        try {
            // 检查是否需要迁移旧数据（处理并发/竞态情况）
            List<Map<String, Object>> overflowMessages = new ArrayList<>();
            try {
                // 获取添加前的 size，用于判断是否溢出
                Long sizeBefore = redisTemplate.opsForList().size(key);
                int overflowCount = 0;
                if (sizeBefore != null && sizeBefore >= MAX_MESSAGES) {
                    overflowCount = 2;  // 每次添加 2 条消息
                }

                // 提取溢出消息（最旧的 2 条），在 trim 之前获取
                if (overflowCount > 0) {
                    List<String> oldMessages = redisTemplate.opsForList().range(key, 0, overflowCount - 1);
                    if (oldMessages != null) {
                        for (String json : oldMessages) {
                            try {
                                Map<String, Object> msg = objectMapper.readValue(json,
                                        new TypeReference<Map<String, Object>>() {});
                                overflowMessages.add(msg);
                            } catch (JsonProcessingException e) {
                                logger.warn("解析溢出消息失败: {}", e.getMessage());
                            }
                        }
                    }
                }
            } catch (Exception e) {
                // WRONGTYPE 错误，说明是旧格式，触发迁移
                if (e.getMessage() != null && e.getMessage().contains("WRONGTYPE")) {
                    logger.warn("检测到旧格式会话数据，尝试迁移: conversationId={}", conversationId);
                    overflowMessages = migrateFromStringFormat(conversationId, key);
                } else {
                    throw e;
                }
            }

            // 添加用户消息（带时间戳和token估算）
            Map<String, Object> userMsgMap = new HashMap<>();
            userMsgMap.put("role", "user");
            userMsgMap.put("content", userMessage);
            userMsgMap.put("timestamp", currentTimestamp);
            userMsgMap.put("token_estimate", usageQuotaService.estimateTextTokens(userMessage));
            String userJson = objectMapper.writeValueAsString(userMsgMap);
            redisTemplate.opsForList().rightPush(key, userJson);

            // 添加助手回复（带时间戳和token估算）
            Map<String, Object> assistantMsgMap = new HashMap<>();
            assistantMsgMap.put("role", "assistant");
            assistantMsgMap.put("content", response);
            assistantMsgMap.put("timestamp", currentTimestamp);
            assistantMsgMap.put("token_estimate", usageQuotaService.estimateTextTokens(response));
            if (referenceMapping != null && !referenceMapping.isEmpty()) {
                assistantMsgMap.put("referenceMappings", toSerializableReferenceMappings(referenceMapping));
            }
            String assistantJson = objectMapper.writeValueAsString(assistantMsgMap);
            redisTemplate.opsForList().rightPush(key, assistantJson);

            // 限制历史记录长度，保留最近的5轮对话（10条消息）
            Long size = redisTemplate.opsForList().size(key);
            if (size != null && size > MAX_MESSAGES) {
                // 移除最旧的消息，保持最多 MAX_MESSAGES 条
                redisTemplate.opsForList().trim(key, size - MAX_MESSAGES, -1);
            }

            // 刷新 TTL
            redisTemplate.expire(key, Duration.ofDays(7));

            logger.debug("更新会话历史，会话ID: {}, 消息数: {}", conversationId,
                    redisTemplate.opsForList().size(key));

            // 如果有溢出消息，触发长期记忆整合
            if (!overflowMessages.isEmpty()) {
                logger.info("触发记忆整合: userId={}, conversationId={}, 溢出消息数={}",
                        userId, conversationId, overflowMessages.size());
                conversationMemoryService.consolidateMemory(userId, conversationId, overflowMessages);
            }
        } catch (JsonProcessingException e) {
            logger.error("序列化对话消息出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private Map<String, Map<String, Object>> toSerializableReferenceMappings(Map<Integer, ReferenceInfo> referenceMapping) {
        Map<String, Map<String, Object>> serialized = new HashMap<>();
        for (Map.Entry<Integer, ReferenceInfo> entry : referenceMapping.entrySet()) {
            ReferenceInfo detail = entry.getValue();
            Map<String, Object> item = new HashMap<>();
            item.put("fileMd5", detail.fileMd5());
            item.put("fileName", detail.fileName());
            item.put("pageNumber", detail.pageNumber());
            item.put("anchorText", detail.anchorText());
            item.put("retrievalMode", detail.retrievalMode());
            item.put("retrievalLabel", detail.retrievalLabel());
            item.put("retrievalQuery", detail.retrievalQuery());
            item.put("matchedChunkText", detail.matchedChunkText());
            item.put("evidenceSnippet", detail.evidenceSnippet());
            item.put("score", detail.score());
            item.put("chunkId", detail.chunkId());
            serialized.put(String.valueOf(entry.getKey()), item);
        }
        return serialized;
    }

    private List<SearchResult> retrieveRagContext(String userMessage, String userId) {
        if (!isPatentQuery(userMessage)) {
            return searchService.searchWithPermission(userMessage, userId, 5);
        }

        try {
            PatentSearchRequest request = new PatentSearchRequest();
            request.setQuery(userMessage);
            request.setTopK(5);
            List<PatentSearchResult> patentResults = patentSearchService.search(request, userId);
            if (patentResults != null && !patentResults.isEmpty()) {
                logger.info("[ChatRAG] 命中专利检索链路: userId={}, count={}", userId, patentResults.size());
                return patentResults.stream()
                        .map(this::toSearchResult)
                        .toList();
            }
            logger.info("[ChatRAG] 专利检索无结果，不回退通用检索: userId={}", userId);
            return List.of();
        } catch (Exception e) {
            logger.warn("[ChatRAG] 专利检索失败，回退通用检索: userId={}, error={}", userId, e.getMessage(), e);
        }

        return searchService.searchWithPermission(userMessage, userId, 5);
    }

    private boolean isPatentQuery(String userMessage) {
        if (userMessage == null || userMessage.isBlank()) {
            return false;
        }
        String normalized = userMessage.toLowerCase();
        if (PATENT_NUMBER_PATTERN.matcher(normalized).find()) {
            return true;
        }
        return PATENT_QUERY_KEYWORDS.stream().anyMatch(normalized::contains);
    }

    private SearchResult toSearchResult(PatentSearchResult patentResult) {
        String contextText = buildPatentContextText(patentResult);
        String matchedText = patentResult.getTextContent() != null ? patentResult.getTextContent() : contextText;
        return new SearchResult(
                patentResult.getFileMd5(),
                patentResult.getChunkNo(),
                contextText,
                patentResult.getScore(),
                null,
                null,
                false,
                buildPatentFileLabel(patentResult),
                patentResult.getPageNumber(),
                patentResult.getAnchorText(),
                "PATENT_" + safeRetrievalMode(patentResult.getRetrievalMode()),
                matchedText
        );
    }

    private String buildPatentContextText(PatentSearchResult result) {
        StringBuilder builder = new StringBuilder("【专利检索】");
        appendPatentField(builder, "题名", result.getTitle());
        appendPatentField(builder, "公开号", result.getPublicationNo());
        appendPatentField(builder, "申请号", result.getApplicationNo());
        appendPatentField(builder, "申请人", result.getApplicant());
        appendPatentField(builder, "专利类型", result.getPatentType());
        appendPatentField(builder, "来源", describePatentSource(result));
        if (result.getTextContent() != null && !result.getTextContent().isBlank()) {
            builder.append(" 内容: ").append(result.getTextContent().trim());
        }
        return builder.toString();
    }

    private void appendPatentField(StringBuilder builder, String label, String value) {
        if (value != null && !value.isBlank()) {
            builder.append(" ").append(label).append(": ").append(value.trim()).append(";");
        }
    }

    private String describePatentSource(PatentSearchResult result) {
        String sourceType = result.getSourceType();
        if ("CLAIM".equalsIgnoreCase(sourceType) && result.getClaimNo() != null) {
            return (result.isIndependentClaim() ? "独立权利要求" : "权利要求") + result.getClaimNo();
        }
        if ("ABSTRACT".equalsIgnoreCase(sourceType)) {
            return "摘要";
        }
        if ("BIBLIOGRAPHIC".equalsIgnoreCase(sourceType)) {
            return "著录项";
        }
        if ("DESCRIPTION".equalsIgnoreCase(sourceType)) {
            return result.getSectionPath() != null && !result.getSectionPath().isBlank()
                    ? "说明书-" + result.getSectionPath()
                    : "说明书";
        }
        return sourceType != null ? sourceType : "专利片段";
    }

    private String buildPatentFileLabel(PatentSearchResult result) {
        if (result.getPublicationNo() != null && !result.getPublicationNo().isBlank()) {
            return result.getPublicationNo();
        }
        if (result.getApplicationNo() != null && !result.getApplicationNo().isBlank()) {
            return result.getApplicationNo();
        }
        if (result.getTitle() != null && !result.getTitle().isBlank()) {
            return result.getTitle();
        }
        return "patent";
    }

    private String safeRetrievalMode(String retrievalMode) {
        return retrievalMode != null && !retrievalMode.isBlank() ? retrievalMode : "HYBRID";
    }

    private String buildContext(List<SearchResult> searchResults, String sessionId, String userMessage) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 LLM provider 按"无检索结果"逻辑处理
            return "";
        }

        // 创建当前会话的引用映射
        Map<Integer, ReferenceInfo> referenceMapping = new HashMap<>();

        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet.length() > MAX_CONTEXT_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_CONTEXT_SNIPPET_LEN) + "…";
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            String fileMd5 = result.getFileMd5();

            // 格式：[1] (test1.txt | 第5页) 文件内容... 或 [1] (test1.txt) 文件内容...
            // 有页码时显示页码，方便AI引用
            Integer pageNum = result.getPageNumber();
            if (pageNum != null && pageNum > 0) {
                context.append(String.format("[%d] (%s | 第%d页) %s\n", i + 1, fileLabel, pageNum, snippet));
            } else {
                context.append(String.format("[%d] (%s) %s\n", i + 1, fileLabel, snippet));
            }

            // 保存引用编号到MD5的映射
            if (fileMd5 != null) {
                ReferenceInfo detail = buildReferenceInfo(result, fileLabel, userMessage);
                referenceMapping.put(i + 1, detail);
                // 详细日志：记录每个引用编号的映射关系
                logger.info("引用映射: sessionId={}, 引用编号#{}={}, 文件名={}, MD5={}, page={}, retrievalMode={}, chunkId={}",
                    sessionId, i + 1, fileLabel, fileMd5, result.getPageNumber(), detail.retrievalMode(), detail.chunkId());
            }
        }

        // 保存当前会话的引用映射
        sessionReferenceMappings.put(sessionId, referenceMapping);
        logger.info("保存会话 {} 的引用映射，共 {} 条: {}", sessionId, referenceMapping.size(), referenceMapping);

        return context.toString();
    }

    /**
     * 构建长期记忆上下文
     */
    private String buildLongTermMemoryContext(List<LongTermMemory> memories) {
        if (memories == null || memories.isEmpty()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("【长期记忆】\n");
        for (int i = 0; i < memories.size(); i++) {
            LongTermMemory mem = memories.get(i);
            String typeLabel = getMemoryTypeLabel(mem.getMemoryType());
            sb.append(String.format("[记忆%d-%s] %s\n",
                    i + 1, typeLabel, mem.getSummary()));
            if (mem.getDetails() != null && !mem.getDetails().isBlank()) {
                sb.append(String.format("详情: %s\n", mem.getDetails()));
            }
        }
        return sb.toString();
    }

    private String getMemoryTypeLabel(String memoryType) {
        if (memoryType == null) return "未知";
        return switch (memoryType) {
            case LongTermMemory.TYPE_TASK -> "任务";
            case LongTermMemory.TYPE_PREFERENCE -> "偏好";
            case LongTermMemory.TYPE_FACT -> "事实";
            case LongTermMemory.TYPE_EPISODE -> "经验";
            case LongTermMemory.TYPE_CONSTRAINT -> "约束";
            default -> memoryType;
        };
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    private void sendRateLimitMessage(WebSocketSession session, RateLimitExceededException exception) {
        try {
            Map<String, Object> response = Map.of(
                    "code", 429,
                    "message", exception.getMessage(),
                    "retryAfterSeconds", exception.getRetryAfterSeconds()
            );
            session.sendMessage(new TextMessage(objectMapper.writeValueAsString(response)));
        } catch (Exception e) {
            logger.error("发送限流消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);

        // 设置停止标志
        stopFlags.put(sessionId, true);

        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop",
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }

        // 清理停止标志（延迟清理，避免影响当前响应）
        try {
            chatMonitorExecutor.execute(() -> {
                try {
                    Thread.sleep(2000);
                    stopFlags.remove(sessionId);
                    logger.debug("已清理停止标志，会话ID: {}", sessionId);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            });
        } catch (RejectedExecutionException ignore) {
            stopFlags.remove(sessionId);
        }
    }

    /**
     * 根据会话ID和引用编号获取文件MD5
     *
     * @param sessionId WebSocket会话ID
     * @param referenceNumber 引用编号
     * @return 文件MD5，如果找不到则返回null
     */
    public String getReferenceMd5(String sessionId, int referenceNumber) {
        ReferenceInfo detail = getReferenceDetail(sessionId, referenceNumber);
        return detail != null ? detail.fileMd5() : null;
    }

    public ReferenceInfo getReferenceDetail(String sessionId, int referenceNumber) {
        logger.info("查询引用MD5: sessionId={}, referenceNumber=#{}", sessionId, referenceNumber);

        Map<Integer, ReferenceInfo> referenceMapping = sessionReferenceMappings.get(sessionId);
        if (referenceMapping == null) {
            logger.error("未找到会话 {} 的引用映射，当前所有会话: {}", sessionId, sessionReferenceMappings.keySet());
            return null;
        }

        logger.info("会话 {} 的引用映射内容: {}", sessionId, referenceMapping);

        ReferenceInfo detail = referenceMapping.get(referenceNumber);
        if (detail == null) {
            logger.error("会话 {} 中未找到引用编号 #{}, 可用的引用编号: {}", sessionId, referenceNumber, referenceMapping.keySet());
            return null;
        }

        logger.info("成功找到引用映射: sessionId={}, referenceNumber=#{}, fileMd5={}, pageNumber={}",
                sessionId, referenceNumber, detail.fileMd5(), detail.pageNumber());
        return detail;
    }

    private ReferenceInfo buildReferenceInfo(SearchResult result, String fileLabel, String userMessage) {
        String matchedChunkText = trimToMaxLength(
                result.getMatchedChunkText() != null ? result.getMatchedChunkText() : result.getTextContent(),
                MAX_MATCHED_CHUNK_LEN
        );
        String evidenceSnippet = buildEvidenceSnippet(userMessage, result.getAnchorText(), matchedChunkText);

        return new ReferenceInfo(
                result.getFileMd5(),
                fileLabel,
                result.getPageNumber(),
                result.getAnchorText(),
                result.getRetrievalMode(),
                buildRetrievalLabel(result.getRetrievalMode()),
                normalizeEvidenceText(userMessage),
                matchedChunkText,
                evidenceSnippet,
                result.getScore(),
                result.getChunkId()
        );
    }

    private String buildRetrievalLabel(String retrievalMode) {
        if (retrievalMode != null && retrievalMode.toUpperCase().startsWith("PATENT_")) {
            return "专利结构化检索";
        }
        if ("TEXT_ONLY".equalsIgnoreCase(retrievalMode)) {
            return "关键词召回";
        }
        return "混合召回（语义相关 + 关键词命中）";
    }

    private String buildEvidenceSnippet(String userMessage, String anchorText, String matchedChunkText) {
        String normalizedAnchorText = normalizeEvidenceText(anchorText);
        if (!normalizedAnchorText.isBlank()) {
            return trimToMaxLength(normalizedAnchorText, MAX_EVIDENCE_SNIPPET_LEN);
        }

        String normalizedMatchedChunk = normalizeEvidenceText(matchedChunkText);
        if (normalizedMatchedChunk.isBlank()) {
            String normalizedUserMessage = normalizeEvidenceText(userMessage);
            if (!normalizedUserMessage.isBlank()) {
                return trimToMaxLength(normalizedUserMessage, MAX_EVIDENCE_SNIPPET_LEN);
            }
            return "";
        }

        String[] sentences = normalizedMatchedChunk.split("(?<=[。！？!?；;])");
        for (String sentence : sentences) {
            String trimmedSentence = sentence.trim();
            if (trimmedSentence.length() >= 12) {
                return trimToMaxLength(trimmedSentence, MAX_EVIDENCE_SNIPPET_LEN);
            }
        }

        return trimToMaxLength(normalizedMatchedChunk, MAX_EVIDENCE_SNIPPET_LEN);
    }

    private String trimToMaxLength(String value, int maxLength) {
        String normalized = normalizeEvidenceText(value);
        if (normalized.length() <= maxLength) {
            return normalized;
        }
        return normalized.substring(0, maxLength) + "…";
    }

    private String normalizeEvidenceText(String value) {
        return value == null ? "" : value.replaceAll("\\s+", " ").trim();
    }

    /**
     * 清理会话的引用映射
     *
     * @param sessionId WebSocket会话ID
     */
    public void clearSessionReferenceMapping(String sessionId) {
        Map<Integer, ReferenceInfo> removed = sessionReferenceMappings.remove(sessionId);
        if (removed != null) {
            logger.info("清理会话 {} 的引用映射，共 {} 条", sessionId, removed.size());
        }
    }

    public record ReferenceInfo(
            String fileMd5,
            String fileName,
            Integer pageNumber,
            String anchorText,
            String retrievalMode,
            String retrievalLabel,
            String retrievalQuery,
            String matchedChunkText,
            String evidenceSnippet,
            Double score,
            Integer chunkId
    ) {
    }
}
